-- Core schema for Security Gate on Supabase Postgres
-- Tables: pull_requests, scan_results, audit_logs

begin;

create table if not exists public.pull_requests (
    id integer generated by default as identity primary key,
    repo_name varchar not null,
    pr_number integer not null,
    pr_url varchar not null,
    status varchar default 'pending',
    risk_score double precision null,
    verdict varchar null,
    files_changed integer null,
    lines_added integer null,
    lines_deleted integer null,
    author_name varchar null,
    feature_importance jsonb null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.scan_results (
    id integer generated by default as identity primary key,
    pr_id integer not null references public.pull_requests(id) on delete cascade,
    tool varchar not null,
    findings jsonb null,
    severity varchar null,
    summary text null,
    execution_time double precision null,
    severity_counts jsonb null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
    id integer generated by default as identity primary key,
    pr_id integer not null unique references public.pull_requests(id) on delete cascade,
    blockchain_hash varchar null,
    blockchain_tx varchar null,
    decision varchar not null,
    risk_data jsonb null,
    timestamp timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_pull_requests_repo_pr
    on public.pull_requests (repo_name, pr_number);

create index if not exists ix_pull_requests_created_at
    on public.pull_requests (created_at desc);

create index if not exists ix_pull_requests_status
    on public.pull_requests (status);

create index if not exists ix_scan_results_pr_id
    on public.scan_results (pr_id);

create index if not exists ix_scan_results_tool
    on public.scan_results (tool);

create index if not exists ix_scan_results_severity
    on public.scan_results (severity);

create or replace function public.set_pull_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_pull_requests_updated_at on public.pull_requests;
create trigger trg_pull_requests_updated_at
before update on public.pull_requests
for each row
execute function public.set_pull_requests_updated_at();

commit;
